name: Release Build and Upload

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
          - os: windows-latest
            platform: windows
            arch: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Run PyInstaller
        run: |
          python build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AICopilot-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/${{ matrix.platform }}_${{ matrix.arch }}/

  upload-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Verify files exist
        run: |
          if [ ! -f dist/linux_x86_64/AICopilot.bin ]; then
            echo "Linux binary not found!"
            exit 1
          fi
          if [ ! -f dist/windows_x86_64/AICopilot_x86_64.exe ]; then
            echo "Windows binary not found!"
            exit 1
          fi
          echo "All files verified successfully!"

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/linux_x86_64/AICopilot.bin
            dist/windows_x86_64/AICopilot_x86_64.exe
